### ISSUE TITLE
Can't find Readme txt file! 

### ISSUE THREAD

**Issue by hitaspdotnet** [saineshwar/ASP.NET-CORE-MVC-Project-Event-Management#1]

**Comment by saineshwar** [comment]
Here is Link of ReadMe_First.txt file  :-   ;- https://github.com/saineshwar/ASP.NET-CORE-MVC-Project-Event-Management/blob/master/ReadMe_First.txt

**Comment by hitaspdotnet** [comment]
Thanks Sir

**Comment by hitaspdotnet** [comment]
Sir! Do you use the CodeFirst architecture?
I am looking for a subject for my school research
I cant see any Initialize class
For playing around your articles I need create DB manually?

**Comment by saineshwar** [comment]
Its Database First, i have created database and then added Models (classes ) according to it.

**Comment by hitaspdotnet** [comment]
Thanks for answering at Christmas holiday,
Sir If is possible can I have your DB script or MDF file? Or please share a post about this. I unknown your Database design
